"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'
import { TrendingDown, Users, Zap } from 'lucide-react'
import { BlockingRuleTemplate, estimatePairReduction } from '@/lib/blocking/ruleTemplates'

interface RuleImpactVisualizationProps {
    totalRecords: number
    rules: Array<{
        rule: string
        template?: BlockingRuleTemplate
    }>
}

export function RuleImpactVisualization({ totalRecords, rules }: RuleImpactVisualizationProps) {
    // Calculate impact for each rule
    const ruleImpacts = rules.map((r, idx) => {
        if (r.template) {
            const impact = estimatePairReduction(totalRecords, r.template)
            return {
                name: r.template.name.substring(0, 20),
                pairs: impact.blockedPairs,
                reduction: impact.reductionPercent,
                selectivity: r.template.estimatedSelectivity
            }
        }
        // Default estimate for custom rules
        const avgReduction = 95
        const totalPairs = (totalRecords * (totalRecords - 1)) / 2
        return {
            name: `Rule ${idx + 1}`,
            pairs: Math.round(totalPairs * (1 - avgReduction / 100)),
            reduction: avgReduction,
            selectivity: 'medium' as const
        }
    })

    // Overall statistics
    const totalPairs = (totalRecords * (totalRecords - 1)) / 2
    const avgBlockedPairs = ruleImpacts.length > 0
        ? Math.round(ruleImpacts.reduce((sum, r) => sum + r.pairs, 0) / ruleImpacts.length)
        : totalPairs
    const avgReduction = ((totalPairs - avgBlockedPairs) / totalPairs) * 100

    const COLORS = {
        high: '#10b981',
        medium: '#f59e0b',
        low: '#ef4444'
    }

    return (
        <div className="space-y-6">
            {/* Summary Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <Card>
                    <CardHeader className="pb-3">
                        <CardDescription className="flex items-center gap-2">
                            <Users className="h-4 w-4" />
                            Total Records
                        </CardDescription>
                        <CardTitle className="text-2xl">{totalRecords.toLocaleString()}</CardTitle>
                    </CardHeader>
                </Card>

                <Card className="bg-red-50/50 dark:bg-red-950/20">
                    <CardHeader className="pb-3">
                        <CardDescription>Without Blocking</CardDescription>
                        <CardTitle className="text-2xl text-red-600">
                            {totalPairs.toLocaleString()}
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p className="text-xs text-muted-foreground">comparisons</p>
                    </CardContent>
                </Card>

                <Card className="bg-green-50/50 dark:bg-green-950/20">
                    <CardHeader className="pb-3">
                        <CardDescription className="flex items-center gap-2">
                            <TrendingDown className="h-4 w-4" />
                            With Blocking
                        </CardDescription>
                        <CardTitle className="text-2xl text-green-600">
                            {avgBlockedPairs.toLocaleString()}
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p className="text-xs font-semibold text-green-600">
                            {avgReduction.toFixed(1)}% reduction
                        </p>
                    </CardContent>
                </Card>
            </div>

            {/* Rule Comparison Chart */}
            {ruleImpacts.length > 0 && (
                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Zap className="h-5 w-5" />
                            Rule Performance Comparison
                        </CardTitle>
                        <CardDescription>Estimated pairs generated by each rule</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <ResponsiveContainer width="100%" height={300}>
                            <BarChart data={ruleImpacts}>
                                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                                <XAxis
                                    dataKey="name"
                                    className="text-xs"
                                    angle={-45}
                                    textAnchor="end"
                                    height={100}
                                />
                                <YAxis
                                    className="text-xs"
                                    tickFormatter={(value) => {
                                        if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`
                                        if (value >= 1000) return `${(value / 1000).toFixed(1)}K`
                                        return value.toString()
                                    }}
                                />
                                <Tooltip
                                    content={({ active, payload }) => {
                                        if (active && payload && payload.length) {
                                            const data = payload[0].payload
                                            return (
                                                <div className="bg-background border rounded-lg p-3 shadow-lg">
                                                    <p className="font-medium">{data.name}</p>
                                                    <p className="text-sm text-muted-foreground">
                                                        Pairs: {data.pairs.toLocaleString()}
                                                    </p>
                                                    <p className="text-sm text-muted-foreground">
                                                        Reduction: {data.reduction.toFixed(1)}%
                                                    </p>
                                                    <Badge
                                                        className="mt-1"
                                                        style={{ backgroundColor: COLORS[data.selectivity as keyof typeof COLORS] }}
                                                    >
                                                        {data.selectivity} selectivity
                                                    </Badge>
                                                </div>
                                            )
                                        }
                                        return null
                                    }}
                                />
                                <Bar
                                    dataKey="pairs"
                                    fill="#8b5cf6"
                                    radius={[8, 8, 0, 0]}
                                />
                            </BarChart>
                        </ResponsiveContainer>
                    </CardContent>
                </Card>
            )}

            {/* Selectivity Distribution */}
            {ruleImpacts.length > 0 && (
                <Card>
                    <CardHeader>
                        <CardTitle>Selectivity Distribution</CardTitle>
                        <CardDescription>Balance of rule types</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <ResponsiveContainer width="100%" height={250}>
                            <PieChart>
                                <Pie
                                    data={[
                                        {
                                            name: 'High Selectivity',
                                            value: ruleImpacts.filter(r => r.selectivity === 'high').length,
                                            fill: COLORS.high
                                        },
                                        {
                                            name: 'Medium Selectivity',
                                            value: ruleImpacts.filter(r => r.selectivity === 'medium').length,
                                            fill: COLORS.medium
                                        },
                                        {
                                            name: 'Low Selectivity',
                                            value: ruleImpacts.filter(r => r.selectivity === 'low').length,
                                            fill: COLORS.low
                                        }
                                    ].filter(d => d.value > 0)}
                                    cx="50%"
                                    cy="50%"
                                    labelLine={false}
                                    label={({ name, value }) => `${name}: ${value}`}
                                    outerRadius={80}
                                    dataKey="value"
                                >
                                    {[COLORS.high, COLORS.medium, COLORS.low].map((color, index) => (
                                        <Cell key={`cell-${index}`} fill={color} />
                                    ))}
                                </Pie>
                                <Tooltip />
                            </PieChart>
                        </ResponsiveContainer>
                    </CardContent>
                </Card>
            )}

            {/* Recommendations */}
            {ruleImpacts.length > 0 && (
                <Card className="border-blue-500/50 bg-blue-50/50 dark:bg-blue-950/20">
                    <CardHeader>
                        <CardTitle className="text-sm">💡 Recommendations</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-2 text-sm">
                        {avgReduction < 90 && (
                            <p>⚠️ Consider adding more selective rules to reduce comparison load</p>
                        )}
                        {ruleImpacts.filter(r => r.selectivity === 'high').length === 0 && (
                            <p>💡 Add at least one high-selectivity rule (email, ID) for better performance</p>
                        )}
                        {ruleImpacts.filter(r => r.selectivity === 'low').length > 2 && (
                            <p>⚠️ Too many low-selectivity rules may not reduce comparisons enough</p>
                        )}
                        {ruleImpacts.length === 1 && (
                            <p>💡 Add multiple rules (OR logic) to increase recall and catch more matches</p>
                        )}
                        {avgReduction >= 95 && ruleImpacts.length >= 3 && (
                            <p>✅ Great balance! Your rules should provide good performance and recall</p>
                        )}
                    </CardContent>
                </Card>
            )}
        </div>
    )
}
